server:
  port: 9999
spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: product
          # lb代表负载均衡
          uri: lb://mall-product
          predicates:
            - Path=/product/**